### ISSUE TITLE
Events or commands?

### ISSUE THREAD

**Issue by ruudk** [youroff/state_machine#4]
I just discovered this when reading a [blog post](https://dev.to/youroff/state-machines-for-business-np8) and was a bit confused. Maybe I’m wrong, but shouldn’t events be in the paste tense? I feel like what you call events are actually commands?

So command: buy, event: bought.

Or command: wake, event: woken_up

https://medium.com/homeaway-tech-blog/command-events-b8942e251824

**Comment by youroff** [comment]
Hmm... I've never thought about this perspective and I agree that a command as an intent that might turn into an event if performed successfully might be semantically more precise. However, I don't think it really matters too much. Conventionally an event in state_machine is a mere container for possible transitions and it's up for a user to come up with the best naming for "event/command" in a particular business model. But I see how it might be confusing especially that in some cases the same "event" can lead to the very different transitions (and target states respectively). However I consider it a beauty of this implementation: the vast majority of the implementations I encountered were forcing user to be explicit about the target state.

**Comment by ruudk** [comment]
Maybe if `event` was called `trigger` or `on`, it would make more sense.

```elixir
defmodule Cat do
  use StateMachine

  defstruct [:name, :state, hungry: true]

  defmachine field: :state do
    state :asleep
    state :awake
    state :playing
    state :eating, after_enter: &Cat.feed_up/1

    trigger :wake do
      transition from: :asleep, to: :awake
    end

    trigger :give_a_mouse do
      transition from: :awake, to: :playing, unless: &Cat.hungry/1
      transition from: :awake, to: :eating, if: &Cat.hungry/1
      transition from: :playing, to: :eating
    end

    trigger :pet do
      transition from: [:eating, :awake], to: :playing
    end

    trigger :sing_a_lullaby do
      transition from: :awake, to: :asleep
      transition from: :playing, to: :asleep
    end
  end

  def hungry(cat) do
    cat.hungry
  end

  def feed_up(cat) do
    {:ok, %{cat | hungry: false}}
  end
end

cat = %Cat{name: "Thomas", state: :asleep}

{:ok, %Cat{state: :awake}} = Cat.trigger(cat, :wake)
```

The `event` param in `trigger(ctx, event, payload \\ nil)` could be called `name` or `trigger_name`. 

Another approach could be to call it `on :wake do`.

**Comment by youroff** [comment]
Actually I just recalled another reason why I called it event. It almost exactly matches the API of the most popular state machine library from the Ruby world:  https://github.com/aasm/aasm I guess it would be pretty nice to let people transition smoothly if they're coming to Elixir from Ruby, which is probably the majority of new comers.
